tinyMCE.addI18n('pt_br.advanced',{
style_select:"Styles",
font_size:"Font size",
fontdefault:"Font family",
block:"Format",
paragraph:"Paragraph",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Alinhar texto a esquerda",
justifycenter_desc:"Centralizado",
justifyright_desc:"Alinhar texto a direita",
justifyfull_desc:"Justificado",
bullist_desc:"Marcadores",
numlist_desc:"Numeração",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Hiperlink",
unlink_desc:"Remover Link",
image_desc:"Insert/edit image",
cleanup_desc:"Fechamento de Tags HTML",
code_desc:"Visualizar/Editar HTML",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Insert horizontal ruler",
removeformat_desc:"Remover formatação",
custom1_desc:"Your custom description here",
forecolor_desc:"Select text color",
backcolor_desc:"Select background color",
charmap_desc:"Insert custom character",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Image properties",
newdocument_desc:"New document",
help_desc:"Help",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More colors"
});