<input type="{$TYPE_COMP}" name="{$NOME_COMP}" {$SIZE_COMP} {$ONKEYPRESS_COMP} id="{$ID_COMP}" {$STYLE_COMP} {$COMP_ONCLICK} {$ONBLUR_COMP}
class="{$CLASS_COMP}" {$ONCHANGE_COMP} title="{$TITLE_COMP}" {$DIR_COMP} {$MAXLENGTH_COMP} {$LANG_COMP} {$TABINDEX_COMP} {$READONLY} value="{$VALUE_COMP}" {$DISABLED_COMP} />
{$MASK_COMP}
